#!/bin/bash
#
# Commands to submit srun scripts for different initial states
# and loss or no loss

# Inputs to change for each initial state
VSLQBIN=$(pwd)/vslq_readout_tests.py
PY=python3
RTIME=04:00:00
WRITEOPT="wp"
Np=5
READOUTMODE="dual"
JNAME="vslq_readout_${READOUTMODE}"
RUNMODE="run"

# Check if ssub is on the PATH
if [ -z "$(which ssub)" ]
then
    printf "ssub not found. Add it to the PATH environment variable!"
    exit 1
fi

# Loop over the initial states
## Lossless case
for initst in "L0" "L1" "l1L1"
do
    # Call ssub
    ssub --run-type batch --proc-type compute --n-proc 1 --n-nodes 1\
    --batch-time $RTIME\
    --batch-exe "$PY $VSLQBIN -p $WRITEOPT --Np $Np --is_lossy 0 \
                              -s $initst -r $READOUTMODE"\
    --batch-jname ${JNAME}_lossless_$initst --batch-wd $HOME/VSLQ\
    --batch-run $RUNMODE
done

## Lossy case
for initst in "L0" "L1" "l1L1"
do
    # Call ssub
    ssub --run-type batch --proc-type compute --n-proc 1 --n-nodes 1\
    --batch-time $RTIME\
    --batch-exe "$PY $VSLQBIN -p $WRITEOPT --Np $Np --is_lossy 1 \
                              -s $initst -r $READOUTMODE"\
    --batch-jname ${JNAME}_lossy_$initst --batch-wd $HOME/VSLQ\
    --batch-run $RUNMODE
done
